baseurl = "http://schooltransportationsystems.com"
languageCode = "en-us"
title = "School Transportation Systems"
canonifyUrls = "true"
theme = "landing-page-hugo"

[params]
    description = "The student transportation efficiency experts"
    custom_css = ["css/local.css"]


[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:bryan@schooltransportationsystems.com"
# [[params.social]]
#     title = "twitter"
#     icon = "twitter"
#     url = "https://twitter.com/SBootstrap"
# [[params.social]]
#     title = "github"
#     icon = "github"
#     url = "https://github.com/IronSummitMedia/startbootstrap"
# [[params.social]]
#     title = "linkedin"
#     icon = "linkedin"
#     url = "http://linkedin.com/in/yourusername"
